import React, { Fragment } from "react";
//Importamos el archivo SASS para los estilos
import "../../sheet_page/scss/items/style_mapmodalplace.scss";

const MapModalPlace = () => {
  return (
    <Fragment>
      <div className="contenedor-mapmodalplace">
        <h6>Escoja un lugar lugar</h6>
        <img src="/sheet_public/img/2.PNG" usemap="#2" className="imagen" />
        <map name="2">
          <area
            name="area-realidad"
            shape="rect"
            coords="5,7,118,105"
            href="http://www.google.com"
            alt=""
            title=""
            target="_blank"
          />
          <area
            name="area-bar"
            shape="rect"
            coords="6,108,117,204"
            href="http://www.google.com"
            alt=""
            title=""
            target="_blank"
          />
          <area
            name="area-tricaster"
            shape="rect"
            coords="3,207,116,384"
            href="http://www.google.com"
            alt=""
            title=""
            target="_blank"
          />
          <area
            name="area-boplus"
            shape="rect"
            coords="2,385,243,479"
            href="http://www.google.com"
            alt=""
            title=""
            target="_blank"
          />
          <area
            name="area-qdshow"
            shape="rect"
            coords="208,8,483,249"
            href="http://www.google.com"
            alt=""
            title=""
            target="_blank"
          />
          <area
            name="area-presentaciones"
            shape="rect"
            coords="118,279,356,384"
            href="http://www.google.com"
            alt=""
            title=""
            target="_blank"
          />
          <area
            name="area-vestuario"
            shape="rect"
            coords="243,388,356,480"
            href="http://www.google.com"
            alt=""
            title=""
            target="_blank"
          />
          <area
            name="area-soporte"
            shape="rect"
            coords="429,367,594,481"
            href="http://www.google.com"
            alt=""
            title=""
            target="_blank"
          />
          <area
            name="area-edicion"
            shape="rect"
            coords="597,368,740,479"
            href="http://www.google.com"
            alt=""
            title=""
            target="_blank"
          />
          <area
            name="area-freddy"
            shape="rect"
            coords="595,246,741,361"
            href="http://www.google.com"
            alt=""
            title=""
            target="_blank"
          />
          <area
            name="area-silvia"
            shape="rect"
            coords="599,127,739,242"
            href="http://www.google.com"
            alt=""
            title=""
            target="_blank"
          />
          <area
            name="area-radio"
            shape="rect"
            coords="597,9,739,123"
            href="http://www.google.com"
            alt=""
            title=""
            target="_blank"
          />
          <area
            name="area-cocina"
            shape="rect"
            coords="486,5,594,120"
            href="http://www.google.com"
            alt=""
            title=""
            target="_blank"
          />
          <area
            name="area-estudio"
            shape="poly"
            coords="203,9,204,253,352,254,352,274,121,273,121,9"
            href="http://www.google.com"
            alt=""
            title=""
            target="_blank"
          />
          <area
            name="area-pasillo"
            shape="poly"
            coords="487,253,487,127,591,127,592,358,424,359,424,475,362,476,362,254"
            href="http://www.google.com"
            alt=""
            title=""
            target="_blank"
          />
        </map>
      </div>
    </Fragment>
  );
};

export default MapModalPlace;
